#OSS\u5BF9\u8C61\u5B58\u50A8\u914D\u7F6E
oss:
  aliyun:
    accessKeyId:
    accessKeySecret:
    bucketName:
    endpoint:
    bucket:
    expiration: 100 #url\u8FC7\u671F\u65F6\u95F4\uFF0C\u5355\u4F4D\uFF1A\u5E74\uFF0C\u9ED8\u8BA4100\u5E74

spring:
  thymeleaf:
    cache: false

lxt:
  file:
    suffix: '/file/'  #\u6620\u5C04\u672C\u5730\u78C1\u76D8\u76EE\u5F55
    local: '/home/lxt/Desktop/0326/test/'  #\u6620\u5C04\u672C\u5730\u78C1\u76D8\u76EE\u5F55